### ISSUE TITLE
merge CIPM and cipm

### ISSUE THREAD

**Issue by kreetrapper** [clarin-eric/clarin-resource-families#12]
[cipm](https://github.com/clarin-eric/clarin-resource-families/blob/main/corpora/historical-corpora/cipm.json) has been imported from the csv, then [CIPM](https://github.com/clarin-eric/clarin-resource-families/blob/main/corpora/historical-corpora/CIPM.json) has been created additionally. 

To me they seem to point to the same item. 

suggestion to merge them

**Comment by jakoble** [comment]
The imported file has been deleted.
